const cursor=document.querySelector('.cursor-light');
window.addEventListener('mousemove',e=>{if(cursor){cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`}});
const meter=document.querySelector('.scroll-meter span');
window.addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;if(meter)meter.style.height=`${m>0?(scrollY/m)*100:0}%`});
const els=document.querySelectorAll('.mission-grid article,.service-card,.support-panel div,.road-step,.issue-grid button,.line-menu a,.industry-strip span');
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');if(e.target.classList.contains('road-step'))e.target.classList.add('in-view')}}),{threshold:.16});
els.forEach(el=>{el.style.opacity=0;el.style.transform='translateY(28px)';el.style.transition='opacity .75s ease,transform .75s ease';obs.observe(el)});
const st=document.createElement('style');st.textContent='.visible{opacity:1!important;transform:none!important}';document.head.appendChild(st);
const core=document.getElementById('coreButton');
core?.addEventListener('click',()=>{document.querySelectorAll('.system-node').forEach((n,i)=>n.animate([{transform:'scale(1)'},{transform:'scale(1.24)',filter:'brightness(1.8)'},{transform:'scale(1)'}],{duration:780,delay:i*95,easing:'cubic-bezier(.2,.8,.2,1)'}));core.animate([{boxShadow:'0 0 20px #72ecff'},{boxShadow:'0 0 120px #72ecff'},{boxShadow:'0 0 20px #72ecff'}],{duration:1200})});
const scopeStage=document.querySelector('.scope-stage'),scopeText=document.getElementById('scopeText');
document.querySelectorAll('.scope-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.scope-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const part=btn.dataset.mode==='part';scopeStage?.classList.toggle('part',part);if(scopeText)scopeText.textContent=part?'Wi-Fi、防犯、Web、AI活用など、必要な領域だけのご相談にも対応します。':'開設・改善に必要な領域を、ひとつの相談窓口で整理します。'}));
function burst(){const c=['#00a8ff','#72ecff','#fff','#7dffb2','#ffd166'];for(let i=0;i<96;i++){const b=document.createElement('i');b.className='confetti';b.style.left=`${innerWidth/2}px`;b.style.top=`${innerHeight*.45}px`;b.style.background=c[i%c.length];b.style.setProperty('--x',`${(Math.random()-.5)*820}px`);b.style.setProperty('--y',`${Math.random()*760-120}px`);document.body.appendChild(b);setTimeout(()=>b.remove(),2100)}}
const btn=document.getElementById('launchBtn'),status=document.getElementById('launchStatus');
btn?.addEventListener('click',()=>{const s=['回線 接続完了','POS 起動完了','防犯 起動完了','Web 公開完了','照明 点灯','事業所オープン！'];let i=0;btn.disabled=true;document.body.classList.add('launching');const t=setInterval(()=>{status.textContent=s[i++];status.animate([{opacity:.2,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:400});if(i===s.length){clearInterval(t);btn.textContent='オープン完了';document.body.classList.add('launched');burst();setTimeout(()=>document.querySelector('.network')?.scrollIntoView({behavior:'smooth'}),800)}},520)});
